### ISSUE TITLE
Add a system font stack to typography options

### ISSUE THREAD

**Issue by luizbills** [tomusborne/generatepress#20]
Something like:
```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```
reference: https://css-tricks.com/snippets/css/system-font-stack/
