### ISSUE TITLE
Box sizing not consistently applied to editor elements

### ISSUE THREAD

**Issue by iansvo** [tomusborne/generatepress#650]
### Description
The box-sizing property isn't something you can set in our styles builder, and some elements in the editor have it set to content box for some reason. This results in things looking different in the frontend vs backend in some situations. 

### Steps to reproduce
1. Use the hero 7 pattern
2. Change the wrapper to use grid
3. set the first container to height 100%

You'll see that the height exceeds the set image because it's adding height 100% to the 7rem default padding (which is also fuckin huge).

**Comment by frzsombor** [comment]
@iansvo I just wanted to open a new issue on this, but found this one.

On the frontend, GeneratePress adds the following CSS rule:
```
*, ::after, ::before {
    box-sizing: inherit;
}
```

However, this is not applied in the Block Editor, so simply styling a button with fixed height and padding results in it appearing differently in the Block Editor compared to the frontend.

I've reported a similar issue in #660 and I fixed both of these.
I'm already using a custom editor-style.css that contains fixes, improvements and helpers, and I've added the above CSS to the file. I'm adding this file to the Editor simply in the `enqueue_block_editor_assets` action hook and by calling `wp_enqueue_style` in it. The fix for #660 is working well since I reported the issue, currently fixing the `box-sizing` also seems good, but will update this issue if I see any strange.

### References

#### Block Editor
![Image](https://github.com/user-attachments/assets/1e20daaf-1f84-46b2-a948-014d37fa1b0f)

#### Frontend
![Image](https://github.com/user-attachments/assets/7e766981-4632-47b2-9f38-7a4ef142c311)

**Comment by frzsombor** [comment]
Final editor css that fixes the bug:

```css
/* Fix missing box-sizing */
/* This is also added by GeneratePress on the frontend, but not in the editor */
/* This only works in the Editor currently, because WP adds border-box inline on .editor-resizable-editor */
*, ::after, ::before {
	box-sizing: inherit;
}
/* Add border-box on the wrapper for extra safety */
.editor-resizable-editor {
	box-sizing: border-box;
}
/* Also fix missing border-box in iframe */
.block-editor-iframe__html {
	box-sizing: border-box;
}
```
