### ISSUE TITLE
[Question: GenerateBlocks 2.0] Descendant combinator that utilizes pseudo-classes

### ISSUE THREAD

**Issue by tance77** [tomusborne/generatepress#661]
Hello, I'm loving the changes to Generate Press / Generate Blocks V2!! Changes are amazing.

I have a question though. Am able to have a defendant combined with a pseudo class. For example:

```css
  .menu-text:hover .menu-text-dropdown,
  .menu-text:focus-within .men-text-dropdown {
            display: block;
   }
```

To describe what this CSS does it allows you to Hover over an Item in a menu then it changes the display of it's dependent to block which gives you a mega menu type effect.

If this is possible using the editor I would love to know how! 

Thanks
